# PowerShell script for service discovery

# Get the script's directory, contracts repo, and workspace root.
$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$contractsRoot = Resolve-Path (Join-Path $scriptDir "..")
$workspaceRoot = Resolve-Path (Join-Path $contractsRoot "..")

# Path to the report
$reportPath = Join-Path $contractsRoot "specs/001-define-messaging-contracts/discovery-report.md"

# Initialize arrays for services
$includedServices = @()
$excludedServices = @()

# Get MALIEV workspace repositories without absorbing local temp/artifact folders.
$subdirectories = Get-ChildItem -Path $workspaceRoot -Directory |
    Where-Object { $_.Name -like "Maliev.*" -or $_.Name -eq "maliev-gitops" -or $_.Name -eq ".github" -or $_.Name -eq "temp" } |
    Sort-Object Name

foreach ($dir in $subdirectories) {
    # Check for .NET solutions/projects or Python service projects.
    $isService = (Get-ChildItem -Path $dir.FullName -Filter "*.csproj" -Recurse) -or
        (Get-ChildItem -Path $dir.FullName -Filter "*.sln*" -Recurse) -or
        (Get-ChildItem -Path $dir.FullName -Filter "pyproject.toml" -Recurse)

    if ($isService) {
        $includedServices += [PSCustomObject]@{
            ServiceName = $dir.Name
            Path        = $dir.FullName
            Justification = "Contains project or solution file."
        }
    } else {
        $excludedServices += [PSCustomObject]@{
            ServiceName = $dir.Name
            Path        = $dir.FullName
            Justification = "Does not contain .csproj or .sln file."
        }
    }
}

# Generate the markdown report
$markdown = @'
# Service Discovery Report

This report was generated by the `discover-services.ps1` script.

## Included Services

| Service Name | Path | Justification |
| :--- | :--- | :--- |
'@

foreach ($service in $includedServices) {
    $markdown += "`n| $($service.ServiceName) | $($service.Path) | $($service.Justification) |"
}

$markdown += "`n"

$markdown += @'

## Excluded Services

| Service Name | Path | Justification |
| :--- | :--- | :--- |
'@

foreach ($service in $excludedServices) {
    $markdown += "`n| $($service.ServiceName) | $($service.Path) | $($service.Justification) |"
}

# Write the report to the file
Set-Content -Path $reportPath -Value $markdown

Write-Host "Discovery report generated at $reportPath"
