# PowerShell script for service discovery

# Get the script's directory and the parent directory
$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$parentDir = Resolve-Path (Join-Path $scriptDir "..")
$rootDir = Resolve-Path (Join-Path $scriptDir "..") # Assuming script is in a subdirectory of the root

# Path to the report
$reportPath = Join-Path $rootDir "specs/001-define-messaging-contracts/discovery-report.md"

# Initialize arrays for services
$includedServices = @()
$excludedServices = @()

# Get all subdirectories in the parent directory
$subdirectories = Get-ChildItem -Path $parentDir -Directory

foreach ($dir in $subdirectories) {
    # Check for .csproj or .sln files
    $isService = (Get-ChildItem -Path $dir.FullName -Filter "*.csproj" -Recurse) -or (Get-ChildItem -Path $dir.FullName -Filter "*.sln" -Recurse)
    
    if ($isService) {
        $includedServices += [PSCustomObject]@{
            ServiceName = $dir.Name
            Path        = $dir.FullName
            Justification = "Contains .csproj or .sln file."
        }
    } else {
        $excludedServices += [PSCustomObject]@{
            ServiceName = $dir.Name
            Path        = $dir.FullName
            Justification = "Does not contain .csproj or .sln file."
        }
    }
}

# Generate the markdown report
$markdown = @"
# Service Discovery Report

This report was generated by the `discover-services.ps1` script.

## Included Services

| Service Name | Path | Justification |
| :--- | :--- | :--- |
"@

foreach ($service in $includedServices) {
    $markdown += "| $($service.ServiceName) | $($service.Path) | $($service.Justification) |`n"
}

$markdown += @"

## Excluded Services

| Service Name | Path | Justification |
| :--- | :--- | :--- |
"@

foreach ($service in $excludedServices) {
    $markdown += "| $($service.ServiceName) | $($service.Path) | $($service.Justification) |`n"
}

# Write the report to the file
Set-Content -Path $reportPath -Value $markdown

Write-Host "Discovery report generated at $reportPath"