using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.Json;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;

namespace Generator
{
    /// <summary>
    /// Generator program for C# messaging contracts.
    /// </summary>
    class Program
    {
        private static ILogger<Program>? _logger;

        static async Task Main(string[] args)
        {
            using var loggerFactory = LoggerFactory.Create(builder =>
            {
                builder.AddConsole();
            });
            _logger = loggerFactory.CreateLogger<Program>();

            var workspaceRoot = GetWorkspaceRoot(Directory.GetCurrentDirectory());
            var schemaRoot = Path.Combine(workspaceRoot, "contracts", "schemas");
            var outputDir = Path.Combine(workspaceRoot, "generated", "csharp", "Contracts");

            var generator = new ManualCSharpGenerator(schemaRoot, loggerFactory.CreateLogger<ManualCSharpGenerator>());
            var results = await generator.GenerateAsync();

            _logger.LogInformation("Cleaning up output directory...");
            if (Directory.Exists(outputDir))
            {
                Directory.Delete(outputDir, recursive: true);
            }
            Directory.CreateDirectory(outputDir);

            _logger.LogInformation("Writing generated files...");
            foreach (var result in results)
            {
                var targetFile = Path.Combine(outputDir, result.Key);
                var targetDir = Path.GetDirectoryName(targetFile);

                if (targetDir != null && !Directory.Exists(targetDir))
                {
                    Directory.CreateDirectory(targetDir);
                }

                if (File.Exists(targetFile))
                {
                    var existingCode = await File.ReadAllTextAsync(targetFile);
                    if (existingCode == result.Value)
                    {
                        _logger.LogInformation("No changes for {targetFile}", targetFile);
                        continue;
                    }
                }

                await File.WriteAllTextAsync(targetFile, result.Value);
                _logger.LogInformation("Updated {targetFile}", targetFile);
            }

            _logger.LogInformation("[OK] C# contract generation complete.");
        }

        static string GetWorkspaceRoot(string currentDir)
        {
            var dir = new DirectoryInfo(currentDir);
            while (dir != null && !dir.GetFiles("*.slnx").Any() && !dir.GetFiles("*.sln").Any())
            {
                dir = dir.Parent;
            }
            return dir?.FullName ?? throw new DirectoryNotFoundException("Could not find workspace root containing a .slnx or .sln file.");
        }

    }

    /// <summary>
    /// Generates C# contract classes from JSON schemas.
    /// </summary>
    public class ManualCSharpGenerator
    {
        private readonly string _schemaRoot;
        private readonly ILogger<ManualCSharpGenerator> _logger;

        /// <summary>
        /// Initializes a new instance of the ManualCSharpGenerator.
        /// </summary>
        /// <param name="schemaRoot">Path to the JSON schema root directory.</param>
        /// <param name="logger">Logger instance.</param>
        public ManualCSharpGenerator(string schemaRoot, ILogger<ManualCSharpGenerator> logger)
        {
            _schemaRoot = schemaRoot;
            _logger = logger;
        }

        /// <summary>
        /// Generates C# contract files from JSON schemas.
        /// </summary>
        /// <returns>Dictionary of generated filename to content.</returns>
        public async Task<IDictionary<string, string>> GenerateAsync()
        {
            var results = new Dictionary<string, string>();

            // 1. Shared Base File
            var sharedSb = new StringBuilder();
            sharedSb.AppendLine("//----------------------");
            sharedSb.AppendLine("// <auto-generated>");
            sharedSb.AppendLine("//     Generated from schemas");
            sharedSb.AppendLine("// </auto-generated>");
            sharedSb.AppendLine("//----------------------");
            sharedSb.AppendLine();
            sharedSb.AppendLine("#nullable enable");
            sharedSb.AppendLine();
            sharedSb.AppendLine("using System;");
            sharedSb.AppendLine("using System.Text.Json.Serialization;");
            sharedSb.AppendLine();
            sharedSb.AppendLine("namespace Maliev.MessagingContracts.Contracts.Shared");
            sharedSb.AppendLine("{");
            _logger.LogInformation("Generating BaseMessage...");
            await GenerateBaseMessage(sharedSb);
            GenerateMessageTypeEnum(sharedSb);
            sharedSb.AppendLine("}");
            results["MessagingContracts.cs"] = sharedSb.ToString();

            // 2. Domain Files
            var domains = new[] {
                "commands", "orders", "payments", "customers", "iam", "shared",
                "career", "compensation", "compliance", "employee", "leave",
                "lifecycle", "performance", "chatbot", "invoices", "quotations",
                "purchase-orders", "receipts", "materials", "suppliers", "auth",
                "uploads", "pdf", "geometry", "accounting", "delivery", "nda",
                "jobs", "inventory", "pricing", "facility"
            };

            foreach (var domainDir in domains)
            {
                var domainPath = Path.Combine(_schemaRoot, domainDir);
                if (!Directory.Exists(domainPath)) continue;

                var files = Directory.GetFiles(domainPath, "*.json", SearchOption.AllDirectories);
                var filtered = files.Where(f =>
                    !f.EndsWith("base-message.json", StringComparison.OrdinalIgnoreCase) &&
                    !f.EndsWith("envelope.json", StringComparison.OrdinalIgnoreCase) &&
                    !Path.GetFileName(f).Equals("command.json", StringComparison.OrdinalIgnoreCase) &&
                    !Path.GetFileName(f).Equals("domain-event.json", StringComparison.OrdinalIgnoreCase) &&
                    !Path.GetFileName(f).Equals("integration-event.json", StringComparison.OrdinalIgnoreCase)
                ).ToList();

                if (!filtered.Any()) continue;

                var domainSb = new StringBuilder();
                domainSb.AppendLine("//----------------------");
                domainSb.AppendLine("// <auto-generated>");
                domainSb.AppendLine("//     Generated from schemas");
                domainSb.AppendLine("// </auto-generated>");
                domainSb.AppendLine("//----------------------");
                domainSb.AppendLine();
                domainSb.AppendLine("#nullable enable");
                domainSb.AppendLine();
                domainSb.AppendLine("using System;");
                domainSb.AppendLine("using System.Text.Json.Serialization;");
                domainSb.AppendLine("using Maliev.MessagingContracts.Contracts.Shared;"); // Reference shared types
                domainSb.AppendLine();

                var pascalDomain = ToPascalCase(domainDir);
                domainSb.AppendLine($"namespace Maliev.MessagingContracts.Contracts.{pascalDomain}");
                domainSb.AppendLine("{");

                foreach (var file in filtered.OrderBy(f => f))
                {
                    var schemaJson = await File.ReadAllTextAsync(file);
                    var schema = JsonDocument.Parse(schemaJson);
                    var root = schema.RootElement;

                    if (root.TryGetProperty("definitions", out var definitions))
                    {
                        foreach (var definition in definitions.EnumerateObject())
                        {
                            _logger.LogInformation("Generating {className} in {domainDir}...", definition.Name, domainDir);
                            await GenerateMessageClassFromDefinition(domainSb, definition.Value, definition.Name);
                            domainSb.AppendLine();
                        }
                    }
                    else
                    {
                        var className = GetClassName(file);
                        _logger.LogInformation("Generating {className} in {domainDir}...", className, domainDir);
                        await GenerateMessageClass(domainSb, file, className);
                        domainSb.AppendLine();
                    }
                }

                domainSb.AppendLine("}");

                var targetFileName = Path.Combine(pascalDomain, $"{pascalDomain}Events.cs");
                results[targetFileName] = domainSb.ToString();
            }

            return results;
        }

        private async Task GenerateBaseMessage(StringBuilder sb)
        {
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// The base structure that all Maliev messaging contracts MUST adhere to.");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    /// <param name=\"MessageId\">Unique identifier for the message.</param>");
            sb.AppendLine("    /// <param name=\"MessageName\">Descriptive name of the message.</param>");
            sb.AppendLine("    /// <param name=\"MessageType\">The type of message (Command, Event, etc.).</param>");
            sb.AppendLine("    /// <param name=\"MessageVersion\">Semantic version of the message contract.</param>");
            sb.AppendLine("    /// <param name=\"PublishedBy\">The service that published the message.</param>");
            sb.AppendLine("    /// <param name=\"ConsumedBy\">List of services intended to consume the message.</param>");
            sb.AppendLine("    /// <param name=\"CorrelationId\">Id used to correlate related messages across a flow.</param>");
            sb.AppendLine("    /// <param name=\"CausationId\">Id of the message that caused this one.</param>");
            sb.AppendLine("    /// <param name=\"OccurredAtUtc\">Timestamp of when the message occurred.</param>");
            sb.AppendLine("    /// <param name=\"IsPublic\">True if the message is intended for external systems.</param>");
            sb.AppendLine("    public record BaseMessage(");
            sb.AppendLine("        [property: JsonPropertyName(\"messageId\")] System.Guid MessageId,");
            sb.AppendLine("        [property: JsonPropertyName(\"messageName\")] string MessageName,");
            sb.AppendLine("        [property: JsonPropertyName(\"messageType\")] MessageType MessageType,");
            sb.AppendLine("        [property: JsonPropertyName(\"messageVersion\")] string MessageVersion,");
            sb.AppendLine("        [property: JsonPropertyName(\"publishedBy\")] string PublishedBy,");
            sb.AppendLine("        [property: JsonPropertyName(\"consumedBy\")] System.Collections.Generic.IReadOnlyList<string> ConsumedBy,");
            sb.AppendLine("        [property: JsonPropertyName(\"correlationId\")] System.Guid CorrelationId,");
            sb.AppendLine("        [property: JsonPropertyName(\"causationId\")] System.Guid? CausationId,");
            sb.AppendLine("        [property: JsonPropertyName(\"occurredAtUtc\")] System.DateTimeOffset OccurredAtUtc,");
            sb.AppendLine("        [property: JsonPropertyName(\"isPublic\")] bool IsPublic)");
            sb.AppendLine("    {");
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// Parameterless constructor for deserialization.");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        public BaseMessage() : this(default(System.Guid), string.Empty, default(MessageType), string.Empty, string.Empty, Array.Empty<string>(), default(System.Guid), default, default(System.DateTimeOffset), default(bool)) { }");
            sb.AppendLine("    }");
        }

        private void GenerateMessageTypeEnum(StringBuilder sb)
        {
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// Defines the types of messages supported in the MALIEV messaging system.");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    [JsonConverter(typeof(JsonStringEnumConverter))]");
            sb.AppendLine("    public enum MessageType");
            sb.AppendLine("    {");
            sb.AppendLine("        /// <summary>Represents a request to perform an action.</summary>");
            sb.AppendLine("        Command,");
            sb.AppendLine("        /// <summary>Represents notification of a fact that has occurred.</summary>");
            sb.AppendLine("        Event,");
            sb.AppendLine("        /// <summary>Represents a request for information.</summary>");
            sb.AppendLine("        Request,");
            sb.AppendLine("        /// <summary>Represents a response to a request.</summary>");
            sb.AppendLine("        Response");
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        private async Task GenerateMessageClass(StringBuilder sb, string schemaFile, string className)
        {
            var schemaJson = await File.ReadAllTextAsync(schemaFile);
            var schema = JsonDocument.Parse(schemaJson);
            var root = schema.RootElement;

            // Get description/title
            if (root.TryGetProperty("description", out var desc))
            {
                sb.AppendLine("    /// <summary>");
                sb.AppendLine($"    /// {desc.GetString()}");
                sb.AppendLine("    /// </summary>");
            }
            else if (root.TryGetProperty("title", out var title))
            {
                sb.AppendLine("    /// <summary>");
                sb.AppendLine($"    /// {title.GetString()}");
                sb.AppendLine("    /// </summary>");
            }

            // Check if this inherits from BaseMessage
            bool inheritsFromBase = false;
            if (root.TryGetProperty("allOf", out var allOf))
            {
                foreach (var item in allOf.EnumerateArray())
                {
                    if (item.TryGetProperty("$ref", out var refProp))
                    {
                        var refValue = refProp.GetString();
                        if (refValue != null && refValue.Contains("base-message"))
                        {
                            inheritsFromBase = true;
                            break;
                        }
                    }
                }
            }

            if (inheritsFromBase)
            {
                // Generate as derived class from BaseMessage
                await GenerateDerivedMessage(sb, root, className);
            }
            else
            {
                // Generate as standalone class
                await GenerateStandaloneMessage(sb, root, className);
            }

            sb.AppendLine();
        }

        private async Task GenerateMessageClassFromDefinition(StringBuilder sb, JsonElement definition, string className)
        {
            // Get description from definition
            string description = "";
            if (definition.TryGetProperty("description", out var desc))
            {
                description = desc.GetString() ?? "";
            }

            GeneratePayloadRecord(sb, definition, $"{className}Payload");

            // Now generate the full event message that derives from BaseMessage
            if (!string.IsNullOrEmpty(description))
            {
                sb.AppendLine("    /// <summary>");
                sb.AppendLine($"    /// {description}");
                sb.AppendLine("    /// </summary>");
            }
            sb.AppendLine("    /// <param name=\"MessageId\">Unique identifier for the message.</param>");
            sb.AppendLine("    /// <param name=\"MessageName\">Descriptive name of the message.</param>");
            sb.AppendLine("    /// <param name=\"MessageType\">The type of message (Command, Event, etc.).</param>");
            sb.AppendLine("    /// <param name=\"MessageVersion\">Semantic version of the message contract.</param>");
            sb.AppendLine("    /// <param name=\"PublishedBy\">The service that published the message.</param>");
            sb.AppendLine("    /// <param name=\"ConsumedBy\">List of services intended to consume the message.</param>");
            sb.AppendLine("    /// <param name=\"CorrelationId\">Id used to correlate related messages across a flow.</param>");
            sb.AppendLine("    /// <param name=\"CausationId\">Id of the message that caused this one.</param>");
            sb.AppendLine("    /// <param name=\"OccurredAtUtc\">Timestamp of when the message occurred.</param>");
            sb.AppendLine("    /// <param name=\"IsPublic\">True if the message is intended for external systems.</param>");
            sb.AppendLine("    /// <param name=\"Payload\">The specific data associated with this message.</param>");
            sb.AppendLine($"    public record {className}(");

            // Base class parameters first
            var baseParams = new[]
            {
                "System.Guid MessageId",
                "string MessageName",
                "MessageType MessageType",
                "string MessageVersion",
                "string PublishedBy",
                "System.Collections.Generic.IReadOnlyList<string> ConsumedBy",
                "System.Guid CorrelationId",
                "System.Guid? CausationId",
                "System.DateTimeOffset OccurredAtUtc",
                "bool IsPublic"
            };

            var allParams = baseParams.ToList();
            allParams.Add($"[property: JsonPropertyName(\"payload\")] {className}Payload Payload");

            for (int i = 0; i < allParams.Count; i++)
            {
                sb.Append($"        {allParams[i]}");
                if (i < allParams.Count - 1)
                {
                    sb.AppendLine(",");
                }
            }
            sb.AppendLine(") : BaseMessage(MessageId, MessageName, MessageType, MessageVersion, PublishedBy, ConsumedBy, CorrelationId, CausationId, OccurredAtUtc, IsPublic)");
            sb.AppendLine("    {");
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// Parameterless constructor for deserialization.");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine($"        public {className}() : this(default(System.Guid), string.Empty, default(MessageType), string.Empty, string.Empty, Array.Empty<string>(), default(System.Guid), default, default(System.DateTimeOffset), default(bool), default!) {{ }}");
            sb.AppendLine("    }");
        }

        private void GeneratePayloadRecord(StringBuilder sb, JsonElement schema, string typeName)
        {
            var properties = new List<(string Name, string JsonName, string Type, string Description)>();

            if (schema.TryGetProperty("properties", out var props))
            {
                foreach (var prop in props.EnumerateObject())
                {
                    var propName = ToPascalCase(prop.Name);
                    var jsonName = prop.Name;
                    string propType;
                    string propDescription = "";

                    if (prop.Value.TryGetProperty("description", out var pDesc))
                    {
                        propDescription = pDesc.GetString() ?? "";
                    }

                    // Extract the actual type string, handling nullable arrays
                    var typeStr = GetTypeString(prop.Value);

                    if (typeStr == "object" &&
                        prop.Value.TryGetProperty("properties", out var nestedProps))
                    {
                        var nestedTypeName = $"{typeName}{propName}";
                        GeneratePayloadRecord(sb, prop.Value, nestedTypeName);
                        propType = nestedTypeName;
                    }
                    else if (typeStr == "array" &&
                             prop.Value.TryGetProperty("items", out var itemsEl))
                    {
                        var itemTypeStr = GetTypeString(itemsEl);
                        if (itemTypeStr == "object")
                        {
                            var itemTypeName = $"{typeName}{propName}Item";
                            GeneratePayloadRecord(sb, itemsEl, itemTypeName);
                            propType = $"System.Collections.Generic.IReadOnlyList<{itemTypeName}>";
                        }
                        else
                        {
                            propType = GetCSharpType(prop.Value, propName);
                        }
                    }
                    else
                    {
                        propType = GetCSharpType(prop.Value, propName);
                    }

                    properties.Add((propName, jsonName, propType, propDescription));
                }
            }

            sb.AppendLine("    /// <summary>");
            sb.AppendLine($"    /// Payload data for {typeName.Replace("Payload", "")}.");
            sb.AppendLine("    /// </summary>");
            foreach (var prop in properties)
            {
                var description = string.IsNullOrEmpty(prop.Description)
                    ? GenerateDescriptionFromPropertyName(prop.Name)
                    : prop.Description;
                sb.AppendLine($"    /// <param name=\"{prop.Name}\">{description}</param>");
            }

            sb.AppendLine($"    public record {typeName}(");
            for (int i = 0; i < properties.Count; i++)
            {
                sb.Append($"        [property: JsonPropertyName(\"{properties[i].JsonName}\")] {properties[i].Type} {properties[i].Name}");
                if (i < properties.Count - 1)
                {
                    sb.AppendLine(",");
                }
            }
            sb.AppendLine(")");
            sb.AppendLine("    {");
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// Parameterless constructor for deserialization.");
            sb.AppendLine("        /// </summary>");
            sb.Append($"        public {typeName}() : this(");
            var defaultValues = properties.Select(p => GetDefaultValue(p.Type)).ToArray();
            sb.Append(string.Join(", ", defaultValues));
            sb.AppendLine(") { }");
            sb.AppendLine("    }");
        }

        private string GetTypeString(JsonElement element)
        {
            if (element.TryGetProperty("type", out var typeProp))
            {
                if (typeProp.ValueKind == JsonValueKind.Array)
                {
                    return typeProp.EnumerateArray()
                        .Select(t => t.GetString())
                        .Where(t => t != null)
                        .FirstOrDefault(t => t != "null") ?? "object";
                }
                return typeProp.GetString() ?? "object";
            }
            return "object";
        }


        private async Task GenerateDerivedMessage(StringBuilder sb, JsonElement root, string className)
        {
            // Extract the payload schema and generate nested types if needed
            var properties = new List<(string Name, string JsonName, string Type, bool Required, string Description)>();
            var requiredProps = new HashSet<string>();

            if (root.TryGetProperty("required", out var reqArray))
            {
                foreach (var req in reqArray.EnumerateArray())
                {
                    requiredProps.Add(req.GetString() ?? "");
                }
            }

            if (root.TryGetProperty("properties", out var props))
            {
                foreach (var prop in props.EnumerateObject())
                {
                    var propName = ToPascalCase(prop.Name);
                    var jsonName = prop.Name;
                    string propDescription = "";
                    if (prop.Value.TryGetProperty("description", out var pDesc))
                    {
                        propDescription = pDesc.GetString() ?? "";
                    }

                    // Check if this is a payload object and generate nested type
                    string propType;
                    var typeStr = GetTypeString(prop.Value);
                    if (typeStr == "object" &&
                        prop.Value.TryGetProperty("properties", out var nestedProps))
                    {
                        // Generate nested record
                        var nestedTypeName = propName.Equals("Payload", StringComparison.OrdinalIgnoreCase)
                            ? $"{className}Payload"
                            : $"{className}{propName}";

                        GenerateNestedRecord(sb, nestedTypeName, prop.Value);

                        // Handle nullability
                        if (prop.Value.TryGetProperty("type", out var typesProp) &&
                            typesProp.ValueKind == JsonValueKind.Array &&
                            typesProp.EnumerateArray().Any(t => t.ValueKind == JsonValueKind.String && t.GetString() == "null"))
                        {
                            propType = $"{nestedTypeName}?";
                        }
                        else
                        {
                            propType = nestedTypeName;
                        }
                    }
                    else if (typeStr == "array" &&
                             prop.Value.TryGetProperty("items", out var itemsEl))
                    {
                        var itemTypeStr = GetTypeString(itemsEl);
                        if (itemTypeStr == "object")
                        {
                            // Generate record for array items
                            var itemTypeName = $"{className}{propName}Item";
                            GenerateNestedRecord(sb, itemTypeName, itemsEl);
                            propType = $"System.Collections.Generic.IReadOnlyList<{itemTypeName}>";
                        }
                        else
                        {
                            propType = GetCSharpType(prop.Value, propName);
                        }
                    }
                    else
                    {
                        propType = GetCSharpType(prop.Value, propName);
                    }

                    var isRequired = requiredProps.Contains(prop.Name);
                    properties.Add((propName, jsonName, propType, isRequired, propDescription));
                }
            }

            // Generate the message record that extends BaseMessage
            sb.AppendLine("    /// <param name=\"MessageId\">Unique identifier for the message.</param>");
            sb.AppendLine("    /// <param name=\"MessageName\">Descriptive name of the message.</param>");
            sb.AppendLine("    /// <param name=\"MessageType\">The type of message (Command, Event, etc.).</param>");
            sb.AppendLine("    /// <param name=\"MessageVersion\">Semantic version of the message contract.</param>");
            sb.AppendLine("    /// <param name=\"PublishedBy\">The service that published the message.</param>");
            sb.AppendLine("    /// <param name=\"ConsumedBy\">List of services intended to consume the message.</param>");
            sb.AppendLine("    /// <param name=\"CorrelationId\">Id used to correlate related messages across a flow.</param>");
            sb.AppendLine("    /// <param name=\"CausationId\">Id of the message that caused this one.</param>");
            sb.AppendLine("    /// <param name=\"OccurredAtUtc\">Timestamp of when the message occurred.</param>");
            sb.AppendLine("    /// <param name=\"IsPublic\">True if the message is intended for external systems.</param>");
            foreach (var prop in properties)
            {
                var description = string.IsNullOrEmpty(prop.Description)
                    ? GenerateDescriptionFromPropertyName(prop.Name)
                    : prop.Description;
                sb.AppendLine($"    /// <param name=\"{prop.Name}\">{description}</param>");
            }
            sb.AppendLine($"    public record {className}(");

            // Base class parameters first
            var baseParams = new[]
            {
                "System.Guid MessageId",
                "string MessageName",
                "MessageType MessageType",
                "string MessageVersion",
                "string PublishedBy",
                "System.Collections.Generic.IReadOnlyList<string> ConsumedBy",
                "System.Guid CorrelationId",
                "System.Guid? CausationId",
                "System.DateTimeOffset OccurredAtUtc",
                "bool IsPublic"
            };

            var allParams = baseParams.ToList();
            foreach (var (Name, JsonName, Type, _, _) in properties)
            {
                allParams.Add($"[property: JsonPropertyName(\"{JsonName}\")] {Type} {Name}");
            }

            for (int i = 0; i < allParams.Count; i++)
            {
                sb.Append($"        {allParams[i]}");
                if (i < allParams.Count - 1)
                {
                    sb.AppendLine(",");
                }
            }
            sb.AppendLine(") : BaseMessage(MessageId, MessageName, MessageType, MessageVersion, PublishedBy, ConsumedBy, CorrelationId, CausationId, OccurredAtUtc, IsPublic)");
            sb.AppendLine("    {");
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// Parameterless constructor for deserialization.");
            sb.AppendLine("        /// </summary>");
            sb.Append($"        public {className}() : this(default(System.Guid), string.Empty, default(MessageType), string.Empty, string.Empty, Array.Empty<string>(), default(System.Guid), default, default(System.DateTimeOffset), default(bool)");
            foreach (var (_, _, Type, _, _) in properties)
            {
                sb.Append($", {GetDefaultValue(Type)}");
            }
            sb.AppendLine(") { }");
            sb.AppendLine("    }");
        }

        private void GenerateNestedRecord(StringBuilder sb, string typeName, JsonElement schema)
        {
            var properties = new List<(string Name, string JsonName, string Type, string Description)>();

            if (schema.TryGetProperty("properties", out var props))
            {
                foreach (var prop in props.EnumerateObject())
                {
                    var propName = ToPascalCase(prop.Name);
                    var jsonName = prop.Name;
                    string propType;
                    string propDescription = "";
                    if (prop.Value.TryGetProperty("description", out var pDesc))
                    {
                        propDescription = pDesc.GetString() ?? "";
                    }

                    var typeStr = GetTypeString(prop.Value);
                    if (typeStr == "object" &&
                        prop.Value.TryGetProperty("properties", out var nestedProps))
                    {
                        var nestedTypeName = $"{typeName}{propName}";
                        GenerateNestedRecord(sb, nestedTypeName, prop.Value);
                        propType = nestedTypeName;
                    }
                    else if (typeStr == "array" &&
                             prop.Value.TryGetProperty("items", out var itemsEl))
                    {
                        var itemTypeStr = GetTypeString(itemsEl);
                        if (itemTypeStr == "object")
                        {
                            var itemTypeName = $"{typeName}{propName}Item";
                            GenerateNestedRecord(sb, itemTypeName, itemsEl);
                            propType = $"System.Collections.Generic.IReadOnlyList<{itemTypeName}>";
                        }
                        else
                        {
                            propType = GetCSharpType(prop.Value, propName);
                        }
                    }
                    else
                    {
                        propType = GetCSharpType(prop.Value, propName);
                    }

                    properties.Add((propName, jsonName, propType, propDescription));
                }
            }

            sb.AppendLine("    /// <summary>");
            sb.AppendLine($"    /// Nested data for {typeName}.");
            sb.AppendLine("    /// </summary>");
            foreach (var prop in properties)
            {
                var description = string.IsNullOrEmpty(prop.Description)
                    ? GenerateDescriptionFromPropertyName(prop.Name)
                    : prop.Description;
                sb.AppendLine($"    /// <param name=\"{prop.Name}\">{description}</param>");
            }

            sb.AppendLine($"    public record {typeName}(");
            for (int i = 0; i < properties.Count; i++)
            {
                sb.Append($"        [property: JsonPropertyName(\"{properties[i].JsonName}\")] {properties[i].Type} {properties[i].Name}");
                if (i < properties.Count - 1)
                {
                    sb.AppendLine(",");
                }
            }
            sb.AppendLine(")");
            sb.AppendLine("    {");
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// Parameterless constructor for deserialization.");
            sb.AppendLine("        /// </summary>");
            sb.Append($"        public {typeName}() : this(");
            var defaultValues = properties.Select(p => GetDefaultValue(p.Type)).ToArray();
            sb.Append(string.Join(", ", defaultValues));
            sb.AppendLine(") { }");
            sb.AppendLine("    }");
        }

        private async Task GenerateStandaloneMessage(StringBuilder sb, JsonElement root, string className)
        {
            var properties = new List<(string Name, string JsonName, string Type, string Description)>();

            if (root.TryGetProperty("properties", out var props))
            {
                foreach (var prop in props.EnumerateObject())
                {
                    var propName = ToPascalCase(prop.Name);
                    var jsonName = prop.Name;
                    string propDescription = "";
                    if (prop.Value.TryGetProperty("description", out var pDesc))
                    {
                        propDescription = pDesc.GetString() ?? "";
                    }

                    // Check for nested objects or arrays of objects to generate types
                    string propType;
                    var typeStr = GetTypeString(prop.Value);
                    if (typeStr == "object" &&
                        prop.Value.TryGetProperty("properties", out var nestedProps))
                    {
                        var nestedTypeName = $"{className}{propName}";
                        GenerateNestedRecord(sb, nestedTypeName, prop.Value);
                        propType = nestedTypeName;
                    }
                    else if (typeStr == "array" &&
                             prop.Value.TryGetProperty("items", out var itemsEl))
                    {
                        var itemTypeStr = GetTypeString(itemsEl);
                        if (itemTypeStr == "object")
                        {
                            var itemTypeName = $"{className}{propName}Item";
                            GenerateNestedRecord(sb, itemTypeName, itemsEl);
                            propType = $"System.Collections.Generic.IReadOnlyList<{itemTypeName}>";
                        }
                        else
                        {
                            propType = GetCSharpType(prop.Value, propName);
                        }
                    }
                    else
                    {
                        propType = GetCSharpType(prop.Value, propName);
                    }

                    properties.Add((propName, jsonName, propType, propDescription));
                }
            }

            foreach (var prop in properties)
            {
                var description = string.IsNullOrEmpty(prop.Description)
                    ? GenerateDescriptionFromPropertyName(prop.Name)
                    : prop.Description;
                sb.AppendLine($"    /// <param name=\"{prop.Name}\">{description}</param>");
            }
            sb.AppendLine($"    public record {className}(");
            for (int i = 0; i < properties.Count; i++)
            {
                sb.Append($"        [property: JsonPropertyName(\"{properties[i].JsonName}\")] {properties[i].Type} {properties[i].Name}");
                if (i < properties.Count - 1)
                {
                    sb.AppendLine(",");
                }
            }
            sb.AppendLine(")");
            sb.AppendLine("    {");
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// Parameterless constructor for deserialization.");
            sb.AppendLine("        /// </summary>");
            sb.Append($"        public {className}() : this(");
            var defaultValues = properties.Select(p => GetDefaultValue(p.Type)).ToArray();
            sb.Append(string.Join(", ", defaultValues));
            sb.AppendLine(") { }");
            sb.AppendLine("    }");
        }

        private string GetCSharpType(JsonElement propertySchema, string propertyName = "")
        {
            if (propertySchema.TryGetProperty("type", out var typeProp))
            {
                string typeStr;
                bool isNullable = false;

                // Handle type arrays like ["string", "null"]
                if (typeProp.ValueKind == JsonValueKind.Array)
                {
                    var types = typeProp.EnumerateArray()
                        .Select(t => t.GetString())
                        .Where(t => t != null)
                        .ToList();
                    isNullable = types.Contains("null");
                    typeStr = types.FirstOrDefault(t => t != "null") ?? "object";
                }
                else
                {
                    typeStr = typeProp.GetString() ?? "object";
                }

                if (typeStr == "object")
                {
                    // Check if it has properties (it's a complex type)
                    if (propertySchema.TryGetProperty("properties", out var props))
                    {
                        // This is a nested type - for payloads, we'll use a descriptive name
                        if (propertyName.Equals("Payload", StringComparison.OrdinalIgnoreCase))
                        {
                            // Return a generic payload record type
                            // We'll enhance this later to generate nested records
                            return "object";
                        }
                        return "object";
                    }
                    return "object";
                }
                else if (typeStr == "string")
                {
                    if (propertySchema.TryGetProperty("format", out var format))
                    {
                        var formatStr = format.GetString();
                        if (formatStr == "uuid") return isNullable ? "System.Guid?" : "System.Guid";
                        if (formatStr == "date-time") return isNullable ? "System.DateTimeOffset?" : "System.DateTimeOffset";
                        if (formatStr == "email") return isNullable ? "string?" : "string";
                    }
                    return isNullable ? "string?" : "string";
                }
                else if (typeStr == "number")
                {
                    return isNullable ? "double?" : "double";
                }
                else if (typeStr == "integer")
                {
                    return isNullable ? "int?" : "int";
                }
                else if (typeStr == "boolean")
                {
                    return isNullable ? "bool?" : "bool";
                }
                else if (typeStr == "array")
                {
                    if (propertySchema.TryGetProperty("items", out var items))
                    {
                        var itemType = GetCSharpType(items);
                        return $"System.Collections.Generic.IReadOnlyList<{itemType}>";
                    }
                    return "System.Collections.Generic.IReadOnlyList<object>";
                }
            }

            return "object";
        }

        private string GetDefaultValue(string csharpType)
        {
            // Handle nullable types
            if (csharpType.EndsWith("?"))
            {
                return "default";
            }

            // Handle collection types - extract the inner type and create properly typed Array.Empty
            if (csharpType.StartsWith("System.Collections.Generic.IReadOnlyList<"))
            {
                // Extract type between < and >
                var innerType = csharpType.Substring(
                    "System.Collections.Generic.IReadOnlyList<".Length,
                    csharpType.Length - "System.Collections.Generic.IReadOnlyList<".Length - 1);
                return $"Array.Empty<{innerType}>()";
            }

            // Handle specific types with explicit typing to avoid ambiguity
            return csharpType switch
            {
                "string" => "string.Empty",
                "System.Guid" => "default(System.Guid)",
                "System.DateTimeOffset" => "default(System.DateTimeOffset)",
                "int" => "default(int)",
                "double" => "default(double)",
                "bool" => "default(bool)",
                "MessageType" => "default(MessageType)",
                _ when csharpType.EndsWith("Payload") || csharpType.Contains("Item") => "default!",
                _ => "default!"
            };
        }

        private string ToPascalCase(string input)
        {
            if (string.IsNullOrEmpty(input)) return input;

            // Handle kebab-case and snake_case
            if (input.Contains('-') || input.Contains('_'))
            {
                var words = input.Split(new[] { '-', '_' }, StringSplitOptions.RemoveEmptyEntries);
                return string.Join("", words.Select(w =>
                    CultureInfo.InvariantCulture.TextInfo.ToTitleCase(w.ToLower())));
            }

            // Handle camelCase - just capitalize the first letter
            return char.ToUpper(input[0]) + input.Substring(1);
        }

        private string GetClassName(string filePath)
        {
            var baseName = Path.GetFileNameWithoutExtension(filePath);
            return string.Join("", baseName.Split('-').Select(w => ToPascalCase(w)));
        }

        private string GenerateDescriptionFromPropertyName(string propertyName)
        {
            if (string.IsNullOrEmpty(propertyName))
                return "The property value";

            var words = new List<string>();
            var currentWord = new System.Text.StringBuilder();

            foreach (var c in propertyName)
            {
                if (char.IsUpper(c) && currentWord.Length > 0)
                {
                    words.Add(currentWord.ToString());
                    currentWord.Clear();
                }
                currentWord.Append(c);
            }
            if (currentWord.Length > 0)
                words.Add(currentWord.ToString());

            if (words.Count == 0)
                return "The property value";

            var description = string.Join(" ", words);
            description = description.TrimEnd('s');
            return $"The {char.ToLower(description[0])}{description.Substring(1)}";
        }
    }
}
